spring.application.name=reviewForAny
server.port=9099

# Database Configuration (Placeholder)
spring.datasource.url=jdbc:postgresql://db:5432/mydatabase
spring.datasource.username=myuser
spring.datasource.password=mypassword
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# JWT Secret (Min 32 chars)
app.jwt.secret=9a4f2c8d3b7a1e5f9g8h7i6j5k4l3m2n1o0p9q8r7s6t5u4v3w2x1y0z
app.jwt.expiration=86400000